pipeline {
    agent any

    stages {
        stage('Create venv') {
            agent {
                docker {
                    image 'python:3.10.17'
                    reuseNode true
                }
            }
            steps {
                sh '''
                # Wyświetlenie plików i wersji Pythona
                ls -la
                python --version

                # Utworzenie i aktywacja wirtualnego środowiska
                python -m venv venv
                . venv/bin/activate

                # Instalacja zależności w venv
                pip install -r requirements.txt
                '''
            }
        }
        stage('Build') {
            agent {
                docker {
                    image 'python:3.10.17'
                    reuseNode true
                }
            }
            steps {
                sh 'echo "Building the project..."'

            }
        }
        stage("Test"){
            agent {
                docker {
                    image 'python:3.10.17'
                    reuseNode true
                }
            }
            steps {
                sh '''
                # Aktywacja wirtualnego środowiska
                . venv/bin/activate

                # Uruchomienie testów
                python -m unittest discover -s tests
                python -m coverage run -m unittest discover -s tests
                python -m coverage report
                python -m coverage html
                python -m coverage xml
                '''
            }
        }
    }
}
