pipeline {
    agent any

    stages {
        
        stage('Build') {
            agent {
                docker {
                    image 'python:3.10.17'
                    reuseNode true
                }
            }
            steps {
                sh '''
                ls -la
                python --version
                pip install --user -r requirements.txt
                python -m unittest discover -s tests
                python -m coverage run -m unittest discover -s tests
                python -m coverage report
                python -m coverage html
                python -m coverage xml
                
                '''

            }
        }
    }
}
